# Write Kubernetes Deployment Script
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
  labels:
    app: book-catalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: my-fastapi-book-app:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DATABASE_URL
          value: "postgresql://wenzong_sit722_user:opJoTHqOzqQK2kjaYKiDKGpaorF1VEpf@dpg-cqg9kdtds78s73catas0-a.oregon-postgres.render.com/wenzong_sit722"
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: book-catalog